name: Build and deploy

on:
  workflow_dispatch:    # 触发方式 1: 手动触发
  push: # 触发方式 2: push 到 master 分支时自动触发
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true      # 下载子仓库，即主题仓库
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true        # 启用 hugo extend

      - name: Build
        run: hugo --minify

      - name: Setup Python                #配置 python 环境，cosmod 基于 python 开发
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup coscmd               # 安装 coscmd 工具
        run: pip install --user coscmd

      - name: Configure coscmd           # 配置存储桶参数和鉴权
        env:
          SECRET_ID: ${{ secrets.SecretId }}      # SecretId
          SECRET_KEY: ${{ secrets.SecretKey }}    # SecretKey
          BUCKET: ${{ secrets.Bucket }}           # 存储桶名称，在存储桶基本信息中获取
          REGION: ${{ secrets.Region }}           # 存储桶地域，在存储桶基本信息中获取，如 ap-shanghai
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION # 为 coscmd 工具配置存储桶信息

      - name: Upload to COS
        run: coscmd upload -rfs --delete public/ /     #上传 public 中的文件 至 cos 存储桶根目录

      - name: Flush CDN
        env:
          SECRET_ID: ${{ secrets.SecretId }}      # 传入鉴权信息
          SECRET_KEY: ${{ secrets.SecretKey }}
        run: |                                    # 安装 sdk 并运行刷新脚本
          pip install --upgrade tencentcloud-sdk-python
          python flush-dns.py -i $SECRET_ID -k $SECRET_KEY